<?php

namespace Isi\Entity\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class IsiEntityUserCredentialProxy extends \Isi\Entity\UserCredential implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    
    public function __get($attribute)
    {
        $this->_load();
        return parent::__get($attribute);
    }

    public function __set($attribute, $value)
    {
        $this->_load();
        return parent::__set($attribute, $value);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'password', 'salt');
    }
}